// Mocks generated by Mockito 5.4.6 from annotations
// in dragontec/test/features/usuarios/presentation/bloc/usuarios_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dragontec/core/errors/failures.dart' as _i6;
import 'package:dragontec/features/usuarios/domain/entities/usuario.dart'
    as _i7;
import 'package:dragontec/features/usuarios/domain/repositories/usuarios_repository.dart'
    as _i2;
import 'package:dragontec/features/usuarios/domain/usecases/create_usuario.dart'
    as _i8;
import 'package:dragontec/features/usuarios/domain/usecases/get_usuarios.dart'
    as _i4;
import 'package:dragontec/features/usuarios/domain/usecases/update_usuario.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUsuariosRepository_0 extends _i1.SmartFake
    implements _i2.UsuariosRepository {
  _FakeUsuariosRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUsuariosUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsuariosUseCase extends _i1.Mock
    implements _i4.GetUsuariosUseCase {
  @override
  _i2.UsuariosRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUsuariosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeUsuariosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UsuariosRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Usuario>>> call(
    _i4.GetUsuariosParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i7.Usuario>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i7.Usuario>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, List<_i7.Usuario>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i7.Usuario>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Usuario>>>);
}

/// A class which mocks [CreateUsuarioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUsuarioUseCase extends _i1.Mock
    implements _i8.CreateUsuarioUseCase {
  @override
  _i2.UsuariosRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUsuariosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeUsuariosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UsuariosRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>> call(_i7.Usuario? usuario) =>
      (super.noSuchMethod(
            Invocation.method(#call, [usuario]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>>.value(
              _FakeEither_1<_i6.Failure, _i7.Usuario>(
                this,
                Invocation.method(#call, [usuario]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Usuario>(
                    this,
                    Invocation.method(#call, [usuario]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>>);
}

/// A class which mocks [UpdateUsuarioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUsuarioUseCase extends _i1.Mock
    implements _i9.UpdateUsuarioUseCase {
  @override
  _i2.UsuariosRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUsuariosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeUsuariosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UsuariosRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>> call(_i7.Usuario? usuario) =>
      (super.noSuchMethod(
            Invocation.method(#call, [usuario]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>>.value(
              _FakeEither_1<_i6.Failure, _i7.Usuario>(
                this,
                Invocation.method(#call, [usuario]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Usuario>(
                    this,
                    Invocation.method(#call, [usuario]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Usuario>>);
}
