// Mocks generated by Mockito 5.4.6 from annotations
// in dragontec/test/features/agencias/domain/usecases/get_agencias_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dragontec/core/errors/failures.dart' as _i5;
import 'package:dragontec/features/agencias/domain/entities/agencia.dart'
    as _i6;
import 'package:dragontec/features/agencias/domain/repositories/agencias_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AgenciasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgenciasRepository extends _i1.Mock
    implements _i3.AgenciasRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Agencia>>> getAgencias({
    int? page,
    int? perPage,
    int? id,
    String? codigo,
    String? nombre,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAgencias, [], {
              #page: page,
              #perPage: perPage,
              #id: id,
              #codigo: codigo,
              #nombre: nombre,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Agencia>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Agencia>>(
                    this,
                    Invocation.method(#getAgencias, [], {
                      #page: page,
                      #perPage: perPage,
                      #id: id,
                      #codigo: codigo,
                      #nombre: nombre,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Agencia>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Agencia>>(
                    this,
                    Invocation.method(#getAgencias, [], {
                      #page: page,
                      #perPage: perPage,
                      #id: id,
                      #codigo: codigo,
                      #nombre: nombre,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Agencia>>>);
}
