// Mocks generated by Mockito 5.4.6 from annotations
// in dragontec/test/features/tracking/data/repositories/tracking_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dragontec/features/tracking/data/datasources/tracking_remote_datasource.dart'
    as _i3;
import 'package:dragontec/features/tracking/data/models/paquete_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaqueteModel_0 extends _i1.SmartFake implements _i2.PaqueteModel {
  _FakePaqueteModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrackingRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackingRemoteDataSource extends _i1.Mock
    implements _i3.TrackingRemoteDataSource {
  @override
  _i4.Future<_i2.PaqueteModel> getTracking(String? trackingCourier) =>
      (super.noSuchMethod(
            Invocation.method(#getTracking, [trackingCourier]),
            returnValue: _i4.Future<_i2.PaqueteModel>.value(
              _FakePaqueteModel_0(
                this,
                Invocation.method(#getTracking, [trackingCourier]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.PaqueteModel>.value(
              _FakePaqueteModel_0(
                this,
                Invocation.method(#getTracking, [trackingCourier]),
              ),
            ),
          )
          as _i4.Future<_i2.PaqueteModel>);
}
