// Mocks generated by Mockito 5.4.6 from annotations
// in dragontec/test/features/alertas/presentation/pages/crear_alerta_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dragontec/features/agencias/domain/usecases/get_agencias.dart'
    as _i4;
import 'package:dragontec/features/agencias/presentation/bloc/agencias_bloc.dart'
    as _i10;
import 'package:dragontec/features/agencias/presentation/bloc/agencias_event.dart'
    as _i11;
import 'package:dragontec/features/agencias/presentation/bloc/agencias_state.dart'
    as _i5;
import 'package:dragontec/features/alertas/domain/usecases/create_alerta_paquete.dart'
    as _i2;
import 'package:dragontec/features/alertas/presentation/bloc/alertas_bloc.dart'
    as _i6;
import 'package:dragontec/features/alertas/presentation/bloc/alertas_event.dart'
    as _i8;
import 'package:dragontec/features/alertas/presentation/bloc/alertas_state.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCreateAlertaPaqueteUseCase_0 extends _i1.SmartFake
    implements _i2.CreateAlertaPaqueteUseCase {
  _FakeCreateAlertaPaqueteUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlertasState_1 extends _i1.SmartFake implements _i3.AlertasState {
  _FakeAlertasState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAgenciasUseCase_2 extends _i1.SmartFake
    implements _i4.GetAgenciasUseCase {
  _FakeGetAgenciasUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAgenciasState_3 extends _i1.SmartFake implements _i5.AgenciasState {
  _FakeAgenciasState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AlertasBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertasBloc extends _i1.Mock implements _i6.AlertasBloc {
  @override
  _i2.CreateAlertaPaqueteUseCase get createAlertaUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#createAlertaUseCase),
            returnValue: _FakeCreateAlertaPaqueteUseCase_0(
              this,
              Invocation.getter(#createAlertaUseCase),
            ),
            returnValueForMissingStub: _FakeCreateAlertaPaqueteUseCase_0(
              this,
              Invocation.getter(#createAlertaUseCase),
            ),
          )
          as _i2.CreateAlertaPaqueteUseCase);

  @override
  _i3.AlertasState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAlertasState_1(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeAlertasState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AlertasState);

  @override
  _i7.Stream<_i3.AlertasState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.AlertasState>.empty(),
            returnValueForMissingStub: _i7.Stream<_i3.AlertasState>.empty(),
          )
          as _i7.Stream<_i3.AlertasState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void add(_i8.AlertasEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.AlertasEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AlertasState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.AlertasEvent>(
    _i9.EventHandler<E, _i3.AlertasState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i8.AlertasEvent, _i3.AlertasState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i9.Change<_i3.AlertasState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AgenciasBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgenciasBloc extends _i1.Mock implements _i10.AgenciasBloc {
  @override
  _i4.GetAgenciasUseCase get getAgenciasUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAgenciasUseCase),
            returnValue: _FakeGetAgenciasUseCase_2(
              this,
              Invocation.getter(#getAgenciasUseCase),
            ),
            returnValueForMissingStub: _FakeGetAgenciasUseCase_2(
              this,
              Invocation.getter(#getAgenciasUseCase),
            ),
          )
          as _i4.GetAgenciasUseCase);

  @override
  _i5.AgenciasState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAgenciasState_3(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeAgenciasState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.AgenciasState);

  @override
  _i7.Stream<_i5.AgenciasState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.AgenciasState>.empty(),
            returnValueForMissingStub: _i7.Stream<_i5.AgenciasState>.empty(),
          )
          as _i7.Stream<_i5.AgenciasState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void add(_i11.AgenciasEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.AgenciasEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.AgenciasState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.AgenciasEvent>(
    _i9.EventHandler<E, _i5.AgenciasState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i11.AgenciasEvent, _i5.AgenciasState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i9.Change<_i5.AgenciasState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
