// Mocks generated by Mockito 5.4.6 from annotations
// in dragontec/test/features/auth/presentation/pages/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dragontec/features/auth/domain/usecases/check_auth_status.dart'
    as _i5;
import 'package:dragontec/features/auth/domain/usecases/get_current_user.dart'
    as _i4;
import 'package:dragontec/features/auth/domain/usecases/login.dart' as _i2;
import 'package:dragontec/features/auth/domain/usecases/logout.dart' as _i3;
import 'package:dragontec/features/auth/presentation/bloc/auth_bloc.dart'
    as _i7;
import 'package:dragontec/features/auth/presentation/bloc/auth_event.dart'
    as _i9;
import 'package:dragontec/features/auth/presentation/bloc/auth_state.dart'
    as _i6;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginUseCase_0 extends _i1.SmartFake implements _i2.LoginUseCase {
  _FakeLoginUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutUseCase_1 extends _i1.SmartFake implements _i3.LogoutUseCase {
  _FakeLogoutUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCurrentUserUseCase_2 extends _i1.SmartFake
    implements _i4.GetCurrentUserUseCase {
  _FakeGetCurrentUserUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCheckAuthStatusUseCase_3 extends _i1.SmartFake
    implements _i5.CheckAuthStatusUseCase {
  _FakeCheckAuthStatusUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_4 extends _i1.SmartFake implements _i6.AuthState {
  _FakeAuthState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i7.AuthBloc {
  @override
  _i2.LoginUseCase get loginUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#loginUseCase),
            returnValue: _FakeLoginUseCase_0(
              this,
              Invocation.getter(#loginUseCase),
            ),
            returnValueForMissingStub: _FakeLoginUseCase_0(
              this,
              Invocation.getter(#loginUseCase),
            ),
          )
          as _i2.LoginUseCase);

  @override
  _i3.LogoutUseCase get logoutUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#logoutUseCase),
            returnValue: _FakeLogoutUseCase_1(
              this,
              Invocation.getter(#logoutUseCase),
            ),
            returnValueForMissingStub: _FakeLogoutUseCase_1(
              this,
              Invocation.getter(#logoutUseCase),
            ),
          )
          as _i3.LogoutUseCase);

  @override
  _i4.GetCurrentUserUseCase get getCurrentUserUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getCurrentUserUseCase),
            returnValue: _FakeGetCurrentUserUseCase_2(
              this,
              Invocation.getter(#getCurrentUserUseCase),
            ),
            returnValueForMissingStub: _FakeGetCurrentUserUseCase_2(
              this,
              Invocation.getter(#getCurrentUserUseCase),
            ),
          )
          as _i4.GetCurrentUserUseCase);

  @override
  _i5.CheckAuthStatusUseCase get checkAuthStatusUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#checkAuthStatusUseCase),
            returnValue: _FakeCheckAuthStatusUseCase_3(
              this,
              Invocation.getter(#checkAuthStatusUseCase),
            ),
            returnValueForMissingStub: _FakeCheckAuthStatusUseCase_3(
              this,
              Invocation.getter(#checkAuthStatusUseCase),
            ),
          )
          as _i5.CheckAuthStatusUseCase);

  @override
  _i6.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_4(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeAuthState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.AuthState);

  @override
  _i8.Stream<_i6.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i6.AuthState>.empty(),
            returnValueForMissingStub: _i8.Stream<_i6.AuthState>.empty(),
          )
          as _i8.Stream<_i6.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void add(_i9.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.AuthEvent>(
    _i10.EventHandler<E, _i6.AuthState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i9.AuthEvent, _i6.AuthState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i10.Change<_i6.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
