// Mocks generated by Mockito 5.4.6 from annotations
// in dragontec/test/features/usuarios/data/repositories/usuarios_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dragontec/features/usuarios/data/datasources/usuarios_remote_datasource.dart'
    as _i3;
import 'package:dragontec/features/usuarios/data/models/usuario_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUsuarioModel_0 extends _i1.SmartFake implements _i2.UsuarioModel {
  _FakeUsuarioModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UsuariosRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuariosRemoteDataSource extends _i1.Mock
    implements _i3.UsuariosRemoteDataSource {
  @override
  _i4.Future<List<_i2.UsuarioModel>> getUsuarios({
    int? page = 1,
    int? perPage = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsuarios, [], {
              #page: page,
              #perPage: perPage,
            }),
            returnValue: _i4.Future<List<_i2.UsuarioModel>>.value(
              <_i2.UsuarioModel>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.UsuarioModel>>.value(
              <_i2.UsuarioModel>[],
            ),
          )
          as _i4.Future<List<_i2.UsuarioModel>>);

  @override
  _i4.Future<_i2.UsuarioModel> createUsuario(_i2.UsuarioModel? usuario) =>
      (super.noSuchMethod(
            Invocation.method(#createUsuario, [usuario]),
            returnValue: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#createUsuario, [usuario]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#createUsuario, [usuario]),
              ),
            ),
          )
          as _i4.Future<_i2.UsuarioModel>);

  @override
  _i4.Future<_i2.UsuarioModel> updateUsuario(_i2.UsuarioModel? usuario) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsuario, [usuario]),
            returnValue: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#updateUsuario, [usuario]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#updateUsuario, [usuario]),
              ),
            ),
          )
          as _i4.Future<_i2.UsuarioModel>);
}
