// Mocks generated by Mockito 5.4.6 from annotations
// in dragontec/test/features/clientes/domain/usecases/clientes_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dragontec/core/errors/failures.dart' as _i5;
import 'package:dragontec/features/clientes/domain/entities/cliente.dart'
    as _i6;
import 'package:dragontec/features/clientes/domain/repositories/clientes_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClientesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientesRepository extends _i1.Mock
    implements _i3.ClientesRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Cliente>> registrarCliente({
    required String? nombre,
    required String? usuario,
    required String? clave,
    required String? claveConfirmacion,
    String? correo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarCliente, [], {
              #nombre: nombre,
              #usuario: usuario,
              #clave: clave,
              #claveConfirmacion: claveConfirmacion,
              #correo: correo,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Cliente>>.value(
              _FakeEither_0<_i5.Failure, _i6.Cliente>(
                this,
                Invocation.method(#registrarCliente, [], {
                  #nombre: nombre,
                  #usuario: usuario,
                  #clave: clave,
                  #claveConfirmacion: claveConfirmacion,
                  #correo: correo,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Cliente>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Cliente>(
                    this,
                    Invocation.method(#registrarCliente, [], {
                      #nombre: nombre,
                      #usuario: usuario,
                      #clave: clave,
                      #claveConfirmacion: claveConfirmacion,
                      #correo: correo,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Cliente>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> asignarAgencia({
    required int? idAgencia,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#asignarAgencia, [], {#idAgencia: idAgencia}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#asignarAgencia, [], {#idAgencia: idAgencia}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#asignarAgencia, [], {
                      #idAgencia: idAgencia,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
